# Generated by Django 3.1.5 on 2021-01-24 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.TextField(choices=[('APPRAISER', 'Appraiser'), ('CUSTOMER', 'Customer requesting an appraisal')]),
        ),
    ]
